/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AdminRouteImport } from "./routes/admin"
import { Route as AoVivoRouteImport } from "./routes/ao-vivo"
import { Route as HistoricoRouteImport } from "./routes/historico"
import { Route as LiderGeralRouteImport } from "./routes/lider-geral"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as MapaRouteImport } from "./routes/mapa"
import { Route as ModalidadesRouteImport } from "./routes/modalidades"
import { Route as PreviewResumoRouteImport } from "./routes/preview-resumo"
import { Route as RegulamentoRouteImport } from "./routes/regulamento"
import { Route as TelaoRouteImport } from "./routes/telao"
import { Route as AdminIndexRouteImport } from "./routes/admin.index"
import { Route as AdminAvisosRouteImport } from "./routes/admin.avisos"
import { Route as AdminJogosRouteImport } from "./routes/admin.jogos"
import { Route as AdminRegulamentoRouteImport } from "./routes/admin.regulamento"
import { Route as AdminResultadosRouteImport } from "./routes/admin.resultados"
import { Route as AdminSeriesRouteImport } from "./routes/admin.series"
import { Route as AdminTurmasRouteImport } from "./routes/admin.turmas"
import { Route as AdminUnicosRouteImport } from "./routes/admin.unicos"
import { Route as ModalidadesIndexRouteImport } from "./routes/modalidades.index"
import { Route as ModalidadesSlugRouteImport } from "./routes/modalidades.$slug"
import { Route as TurmasIdRouteImport } from "./routes/turmas.$id"
import { Route as PainelJes2026EntradaRouteImport } from "./routes/painel.jes-2026.entrada"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
})
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
})
const AoVivoRoute = AoVivoRouteImport.update({
  id: "/ao-vivo",
  path: "/ao-vivo",
  getParentRoute: () => rootRouteImport,
})
const HistoricoRoute = HistoricoRouteImport.update({
  id: "/historico",
  path: "/historico",
  getParentRoute: () => rootRouteImport,
})
const LiderGeralRoute = LiderGeralRouteImport.update({
  id: "/lider-geral",
  path: "/lider-geral",
  getParentRoute: () => rootRouteImport,
})
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
})
const MapaRoute = MapaRouteImport.update({
  id: "/mapa",
  path: "/mapa",
  getParentRoute: () => rootRouteImport,
})
const ModalidadesRoute = ModalidadesRouteImport.update({
  id: "/modalidades",
  path: "/modalidades",
  getParentRoute: () => rootRouteImport,
})
const PreviewResumoRoute = PreviewResumoRouteImport.update({
  id: "/preview-resumo",
  path: "/preview-resumo",
  getParentRoute: () => rootRouteImport,
})
const RegulamentoRoute = RegulamentoRouteImport.update({
  id: "/regulamento",
  path: "/regulamento",
  getParentRoute: () => rootRouteImport,
})
const TelaoRoute = TelaoRouteImport.update({
  id: "/telao",
  path: "/telao",
  getParentRoute: () => rootRouteImport,
})
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRoute,
})
const AdminAvisosRoute = AdminAvisosRouteImport.update({
  id: "/avisos",
  path: "/avisos",
  getParentRoute: () => AdminRoute,
})
const AdminJogosRoute = AdminJogosRouteImport.update({
  id: "/jogos",
  path: "/jogos",
  getParentRoute: () => AdminRoute,
})
const AdminRegulamentoRoute = AdminRegulamentoRouteImport.update({
  id: "/regulamento",
  path: "/regulamento",
  getParentRoute: () => AdminRoute,
})
const AdminResultadosRoute = AdminResultadosRouteImport.update({
  id: "/resultados",
  path: "/resultados",
  getParentRoute: () => AdminRoute,
})
const AdminSeriesRoute = AdminSeriesRouteImport.update({
  id: "/series",
  path: "/series",
  getParentRoute: () => AdminRoute,
})
const AdminTurmasRoute = AdminTurmasRouteImport.update({
  id: "/turmas",
  path: "/turmas",
  getParentRoute: () => AdminRoute,
})
const AdminUnicosRoute = AdminUnicosRouteImport.update({
  id: "/unicos",
  path: "/unicos",
  getParentRoute: () => AdminRoute,
})
const ModalidadesIndexRoute = ModalidadesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ModalidadesRoute,
})
const ModalidadesSlugRoute = ModalidadesSlugRouteImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => ModalidadesRoute,
})
const TurmasIdRoute = TurmasIdRouteImport.update({
  id: "/turmas/$id",
  path: "/turmas/$id",
  getParentRoute: () => rootRouteImport,
})
const PainelJes2026EntradaRoute = PainelJes2026EntradaRouteImport.update({
  id: "/painel/jes-2026/entrada",
  path: "/painel/jes-2026/entrada",
  getParentRoute: () => rootRouteImport,
})

const AdminRouteChildren = {
  AdminAvisosRoute: AdminAvisosRoute,
  AdminJogosRoute: AdminJogosRoute,
  AdminRegulamentoRoute: AdminRegulamentoRoute,
  AdminResultadosRoute: AdminResultadosRoute,
  AdminSeriesRoute: AdminSeriesRoute,
  AdminTurmasRoute: AdminTurmasRoute,
  AdminUnicosRoute: AdminUnicosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const ModalidadesRouteChildren = {
  ModalidadesSlugRoute: ModalidadesSlugRoute,
  ModalidadesIndexRoute: ModalidadesIndexRoute,
}

const ModalidadesRouteWithChildren = ModalidadesRoute._addFileChildren(
  ModalidadesRouteChildren,
)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AoVivoRoute: AoVivoRoute,
  HistoricoRoute: HistoricoRoute,
  LiderGeralRoute: LiderGeralRoute,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  ModalidadesRoute: ModalidadesRouteWithChildren,
  PreviewResumoRoute: PreviewResumoRoute,
  RegulamentoRoute: RegulamentoRoute,
  TelaoRoute: TelaoRoute,
  TurmasIdRoute: TurmasIdRoute,
  PainelJes2026EntradaRoute: PainelJes2026EntradaRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
